core.symlinks=true
core.autocrlf=true
core.fscache=true
core.usebuiltinfsmonitor=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager-core
http.sslbackend=openssl
http.sslcainfo=C:/laragon/bin/Git/mingw64/ssl/certs/ca-bundle.crt
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\laragon\bin\Microsoft VS Code\bin\code" --wait
user.name=xdotcoid
user.email=satellaff@gmail.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/xdotcoid/tidefy.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
